# Generated by Django 5.0.1 on 2024-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=40)),
                ('Emp_ID', models.IntegerField()),
                ('Designation', models.CharField(max_length=130)),
                ('Date_of_Joining', models.IntegerField()),
                ('Department', models.CharField(max_length=130)),
                ('Salary_Package', models.IntegerField()),
                ('Experience', models.CharField(max_length=130)),
            ],
        ),
    ]
