# Generated by Django 5.0.1 on 2024-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCCATION', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_of_Joining',
            field=models.CharField(max_length=130),
        ),
    ]
