# Generated by Django 5.0.1 on 2024-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_latestnews_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('Occation', models.CharField(max_length=200)),
            ],
        ),
    ]
